version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./database/initdb.d/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
