version: '3.8'

services:
  db:
    image: postgres
    container_name: medical-vaccinate-system-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./database/initdb.d/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
  api:
    build: ./
    container_name: medical-vaccinate-system-api
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URL=//db:5432/vaccinate
    depends_on:
      - db
