spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 321715938529-dn4e8abollqh6g8mtaoucsu9tn6khb6n.apps.googleusercontent.com
            client-secret: E6bRsPG3z4DMpc_DP3aHE6YB
            redirectUri: ${REDIRECT_URI}
  datasource:
    url: jdbc:postgresql:${POSTGRES_URL}
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    hibernate:
      ddl-auto: none
  jackson:
    default-property-inclusion: always
    serialization:
      indent_output: true
      write-dates-as-timestamps: false
  flyway:
    locations: classpath:/flyway

POSTGRES_URL: //localhost:5432/vaccinate
REDIRECT_URI: http://localhost:4200/callback
